version: "3"

services:
    HostA:
        build: ./
        image: seed-ubuntu-base-image
        container_name: host-10.9.0.5
        tty: true
        cap_add:
                - ALL
        volumes:
                - /home/marco/Desktop/ESERCIZI_SICUREZZA/docker/shared_folder_a:/var/www/html/
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

    HostB:
        image: seed-ubuntu-base-image
        container_name: host-10.9.0.6
        tty: true
        cap_add:
                - ALL
        volumes:
                - /home/marco/Desktop/ESERCIZI_SICUREZZA/docker/shared_folder_b:/var/www/html/
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
        


networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
